# Generated by Django 5.1.1 on 2024-09-30 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingapplications',
            name='applicant',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
