# Generated by Django 5.1.1 on 2024-09-29 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_lastmonthlicenses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lastmonthlicenses',
            name='created_at',
        ),
    ]
