# Generated by Django 5.1.1 on 2024-09-30 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_pendingapplications_minerals'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeredapplications',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
