# Generated by Django 5.1.1 on 2024-10-11 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_registeredapplications_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='YearlyCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(blank=True, max_length=255, null=True)),
                ('total', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
