# Generated by Django 5.1.1 on 2024-09-29 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_lastmonthlicenses_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='lastmonthlicenses',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
