# Generated by Django 5.1.1 on 2024-09-29 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_registeredapplications'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeredapplications',
            name='number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
