# Generated by Django 5.1.1 on 2024-11-15 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_coordinates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenses',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
