# Generated by Django 5.1.1 on 2025-07-07 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_licenses_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='licenses',
            name='lga',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='licenses',
            name='minerals',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='licenses',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
