# Generated by Django 5.1.1 on 2024-09-29 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_registered_measures'),
    ]

    operations = [
        migrations.AddField(
            model_name='registered_measures',
            name='number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
